# Generated by Django 4.2.3 on 2023-07-21 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=17, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Optional. For Receipt', max_length=255, null=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255, null=True)),
                ('usertype', models.CharField(choices=[('none', 'None'), ('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager')], default='none', max_length=256)),
                ('isCustomer', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('OTP', models.PositiveIntegerField(blank=True, null=True)),
                ('appversion', models.CharField(blank=True, help_text='To Keep Track of app users', max_length=100, null=True)),
                ('status', models.CharField(choices=[('deleted', 'Deleted'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=100)),
                ('staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('admin', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
